### ISSUE TITLE
Server can not be stopped from within the App in Android 14

### ISSUE THREAD

**Issue by matthias-buchmeier** [umer0586/SensorServer#56] opened 2024-05-03 10:46 UTC
Phone: Samsung Galaxy S22; Android 14; Kernel 5.10.177; One UI version 6.0.

Bug: The server does not stop after activating the stop button on the main screen of the App. The App and server even keep running after closing it. Only "force stop option from Settings/Applications works.

**Comment by umer0586** [comment] 2024-05-05 09:39
- Does this behavior always occur on your device? In other words, have you noticed this happening every time you try to stop the server?
- Are you able to reproduce the same issue on any other Android devices?
- Have you tried clearing the app's cache and storage?

Sometimes clearing an app's cache and storage can resolve temporary glitches.

**Comment by matthias-buchmeier** [comment] 2024-05-06 13:56
The behavior is always reproduced on this device. I never observed it on other devices. Clearing the cache does not help.

**Comment by umer0586** [comment] 2024-05-09 09:23
It sounds like the issue might be specific to your device. 
Have you tried stopping the server from the notification bar?

**Comment by wijaflo** [comment] 2024-06-03 09:05
I'm also unable to stop the connection from within the app. 

Galaxy A52
One UI-Version 6.0
Android Version 14
Kernel 4.14.190

**Comment by umer0586** [comment] 2024-06-04 09:08
@wijaflo 
I don't know why the app is showing such behavior on your and @matthias-buchmeier's device

**Comment by itamark-targa** [comment] 2024-06-07 21:30
Same problem, Galaxy A52s, Android 14
Server still running even if I force close the app,

**Comment by umer0586** [comment] 2024-06-09 07:03
@itamark-targa Noted !

**Comment by umer0586** [comment] 2024-07-23 10:50
This issue has been resolved in [v6.1.1](https://github.com/umer0586/SensorServer/releases/tag/v6.1.1). Please check if the problem still persists on your device.

**Comment by itamark-targa** [comment] 2024-07-25 07:56
> This issue has been resolved in [v6.1.1](https://github.com/umer0586/SensorServer/releases/tag/v6.1.1). Please check if the problem still persists on your device.

Thanks, now the server can be stopped :)
Another issue (not sure if it's related), is that if I close the app (by "up swiping" it) and re-open, pressing the "start" button gives a "port already in use" message. It can be resolved by force-stopping the app.

**Comment by umer0586** [comment] 2024-07-26 12:18
> Another issue (not sure if it's related), is that if I close the app (by "up swiping" it) and re-open, pressing the "start" button gives a "port already in use" message. It can be resolved by force-stopping the app.

I am unable to reproduce this issue on an Android 14 emulator using the following steps:
1. Open the app.
2. Start the server.
3. Close the app by swiping up from the apps list while the server is running.
4. Reopen the app.
5. A message appears: "Service running."
6. Stop the server.
7. Start the server again.
8. A message appears: "Server started."

**Closed** 2024-07-30 03:44 UTC
Labels: bug
